name: Deploy_via_Helm

on:
  workflow_run:
    workflows: ["create_docker_image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Verify helm
        run: helm version

      - name: Verify cluster
        run: kubectl get nodes

      - name: Deploy / Upgrade via Helm
        run: |
          VERSION=${{ github.ref_name }}
          helm upgrade --install my-app my-github-app/ \
          --set githubDemoApp.image.tag=$VERSION

      - name: Verify rollout
        run: |
          kubectl rollout status deployment/my-app -n default